# image: https://hub.docker.com/r/collabora/code/
# docs: https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html


version: '3.8'
services:
  collabora-online:
    container_name: ${APP_NAME}-mysql
    image: collabora/code:${APP_VERSION}
    environment:
     - domain=<your-dot-escaped-domain>
     - username=admin
     - password=S3cRet
    ports:
      - ${APP_PORT}:9980
    tty: true
    restart: always
     
    
networks:
  default:
      name: ${APP_NAME}
    
volumes:
  collabora:
    driver: local
